import type { AIAgent, Philosophy } from './types'

export const INITIAL_AI_AGENTS: AIAgent[] = [
  {
    id: 'owner',
    name: 'オーナーAI',
    role: '代表・全体統括',
    color: '#4f46e5',
    bgLight: '#eef2ff',
    emoji: '👑',
    initials: 'オ',
    description: '事業全体の戦略立案・最終意思決定を担当。各部門の連携を統括し、2号店出店計画を推進します。',
    specialties: ['戦略立案', '意思決定', '投資判断', 'ビジョン策定'],
  },
  {
    id: 'property',
    name: '物件AI',
    role: '物件・立地担当',
    color: '#0891b2',
    bgLight: '#ecfeff',
    emoji: '🏢',
    initials: '物',
    description: '最適な出店候補地の調査・分析を担当。競合調査、商圏分析、契約交渉をサポートします。',
    specialties: ['立地分析', '商圏調査', '契約交渉', '競合調査'],
  },
  {
    id: 'product',
    name: '商品開発AI',
    role: '商品・メニュー担当',
    color: '#16a34a',
    bgLight: '#f0fdf4',
    emoji: '🍽️',
    initials: '商',
    description: '2号店のメニュー開発・品質管理を担当。既存店との差別化と顧客満足度向上を推進します。',
    specialties: ['メニュー開発', '品質管理', '原価管理', '差別化戦略'],
  },
  {
    id: 'finance',
    name: '財務AI',
    role: '財務・経理担当',
    color: '#b45309',
    bgLight: '#fffbeb',
    emoji: '💰',
    initials: '財',
    description: '資金調達・予算管理・収支分析を担当。投資対効果の最大化と財務健全性の確保を支援します。',
    specialties: ['資金調達', '予算管理', '収支分析', '融資相談'],
  },
  {
    id: 'marketing',
    name: 'マーケAI',
    role: 'マーケティング担当',
    color: '#db2777',
    bgLight: '#fdf2f8',
    emoji: '📣',
    initials: 'マ',
    description: '集客・ブランディング・SNS運用を担当。開業前後のプロモーション戦略を立案・実行します。',
    specialties: ['SNS運用', 'ブランディング', '集客施策', 'プロモーション'],
  },
  {
    id: 'audit',
    name: '監査AI',
    role: 'リスク管理・監査',
    color: '#dc2626',
    bgLight: '#fef2f2',
    emoji: '🔍',
    initials: '監',
    isAudit: true,
    description: '全部門のリスク評価・法令遵守・内部統制を担当。計画の整合性と実行可能性を客観的に検証します。',
    specialties: ['リスク評価', 'コンプライアンス', '内部統制', '計画検証'],
  },
]

export const INITIAL_TASK_DATA = [
  {
    id: 't1',
    title: '物件候補地3件のリストアップ',
    description: '半径3km以内の候補物件を調査し、坪数・賃料・立地スコアをまとめる',
    assigneeId: 'property',
    status: '進行中' as const,
    priority: '高' as const,
    timeframe: 'week' as const,
    dueDate: '2026-06-20',
    category: '物件調査',
  },
  {
    id: 't2',
    title: '初期投資試算の作成',
    description: '設備費・内装費・初期在庫・運転資金の見積もりを一覧化する',
    assigneeId: 'finance',
    status: '未着手' as const,
    priority: '高' as const,
    timeframe: 'week' as const,
    dueDate: '2026-06-21',
    category: '財務',
  },
  {
    id: 't3',
    title: 'SNSアカウント開設・プロフィール整備',
    assigneeId: 'marketing',
    status: '完了' as const,
    priority: '中' as const,
    timeframe: 'week' as const,
    category: 'マーケティング',
  },
  {
    id: 't4',
    title: '2号店コンセプトメニューの草案作成',
    description: '既存店との差別化を意識した限定メニュー10品の提案',
    assigneeId: 'product',
    status: '進行中' as const,
    priority: '中' as const,
    timeframe: 'month' as const,
    dueDate: '2026-06-30',
    category: 'メニュー開発',
  },
  {
    id: 't5',
    title: '銀行融資相談・必要書類準備',
    assigneeId: 'finance',
    status: '未着手' as const,
    priority: '高' as const,
    timeframe: 'month' as const,
    dueDate: '2026-07-10',
    category: '資金調達',
  },
  {
    id: 't6',
    title: '競合店の価格・客層調査',
    assigneeId: 'property',
    status: '未着手' as const,
    priority: '中' as const,
    timeframe: 'month' as const,
    category: '市場調査',
  },
  {
    id: 't7',
    title: 'リスクマトリクスの作成',
    assigneeId: 'audit',
    status: '未着手' as const,
    priority: '高' as const,
    timeframe: 'month' as const,
    category: 'リスク管理',
  },
  {
    id: 't8',
    title: '年間事業計画書の策定',
    description: '売上目標・採用計画・投資回収計画を含む事業計画書の作成',
    assigneeId: 'owner',
    status: '未着手' as const,
    priority: '高' as const,
    timeframe: 'year' as const,
    dueDate: '2026-09-01',
    category: '経営計画',
  },
  {
    id: 't9',
    title: '物件契約・内装工事着工',
    assigneeId: 'property',
    status: '未着手' as const,
    priority: '高' as const,
    timeframe: 'year' as const,
    dueDate: '2026-10-01',
    category: '物件',
  },
  {
    id: 't10',
    title: '採用・スタッフ研修プログラム構築',
    assigneeId: 'owner',
    status: '未着手' as const,
    priority: '中' as const,
    timeframe: 'year' as const,
    dueDate: '2026-11-01',
    category: '採用・研修',
  },
  {
    id: 't11',
    title: 'グランドオープンキャンペーン企画',
    assigneeId: 'marketing',
    status: '未着手' as const,
    priority: '中' as const,
    timeframe: 'year' as const,
    dueDate: '2026-11-15',
    category: 'マーケティング',
  },
]

export const INITIAL_PHILOSOPHY: Philosophy = {
  vision: 'すべてのお客様に、料理の感動と笑顔のひとときを',
  mission: '地域に根ざした本物の味と温かいサービスで、日常に豊かさをもたらす飲食店を全国に展開する',
  values: ['品質へのこだわり', '地域への貢献', 'チームワーク', '継続的な成長', '誠実さ'],
}

export const AGENT_ACTIVITIES: Record<string, string[]> = {
  owner: [
    '2号店出店計画の全体スケジュールを見直しています',
    '各部門の進捗レポートを確認しました',
    '投資判断のため財務AIとの協議を予定しています',
    '出店エリアの最終絞り込みを検討中です',
    'ステークホルダーへの報告資料を準備中',
    '1号店の運営状況と2号店計画の比較分析を実施中',
    '出店スケジュール全体を俯瞰し、優先順位を調整中',
  ],
  property: [
    '有望な物件候補地を3件特定しました',
    '商圏内の人口動態データを更新中',
    '競合店舗の出退店情報を収集しています',
    '候補物件の賃料交渉の余地を分析中',
    '駅からの導線と集客ポテンシャルを評価中',
    '物件オーナーとの初回面談のスケジュールを調整中',
    '周辺エリアの平日・休日の人流データを取得しました',
  ],
  product: [
    '2号店向け限定メニューの試作を開始しました',
    '既存メニューの原価率を再計算中',
    '季節限定メニューの企画案を作成しています',
    '食材の仕入れルートを見直し、コスト削減を検討',
    'アレルギー対応メニューの拡充案を検討中',
    '顧客アンケートをもとにメニュー改訂案を作成中',
    '2号店コンセプトに合うスペシャルドリンクを開発中',
  ],
  finance: [
    '初期投資の試算を更新：概算3,200万円',
    '金融機関との融資相談に向けた書類を整備中',
    '損益分岐点の計算を完了。月次売上270万円が目標',
    'キャッシュフロー計画を12ヶ月分作成中',
    '設備投資：リース vs ローン購入を比較検討',
    '税務上の優遇措置が適用できないか調査中',
    '1号店の財務データをもとに2号店の収益モデルを構築中',
  ],
  marketing: [
    'オープン前のSNS集客戦略を策定中',
    'ターゲット顧客層のペルソナ分析を完了しました',
    '地域メディアへのプレスリリース草案を作成',
    '競合店との差別化ポイントを5項目整理しました',
    'インフルエンサーマーケティングの費用対効果を試算中',
    'グランドオープンキャンペーンの企画案を提出準備中',
    'Instagram・TikTokの運用コンテンツカレンダーを作成中',
  ],
  audit: [
    '【監査】初期投資計画に過小見積もりのリスクがあります',
    '【監査】出店エリアの法規制・用途地域を確認しました',
    '【監査】労働基準法に則った雇用契約書の雛形を確認済',
    '【監査】食品衛生法の許可申請手順を整理しました',
    '【監査】競合分析に楽観的バイアスが見られます。再検討を推奨',
    '【監査】融資条件の金利リスクについて財務AIに再確認を依頼',
    '【監査】全部門の計画に矛盾がないか整合性チェックを実施中',
  ],
}

export const QA_TEMPLATES: Record<string, string[]> = {
  owner: [
    '「{topic}」は経営全体に関わる重要課題です。戦略的観点から慎重に判断します。',
    '「{topic}」については1号店の事例を参考にしながら意思決定を進めます。',
    '「{topic}」の優先順位を上げ、今週中に方針を固めます。',
  ],
  property: [
    '「{topic}」について物件・立地の視点で分析します。調査データと照合します。',
    '「{topic}」は商圏特性と密接に関係しています。エリア別データを精査します。',
    '「{topic}」を考慮した物件選定条件を見直します。',
  ],
  product: [
    '「{topic}」はメニュー構成・商品戦略に影響します。開発スケジュールに反映します。',
    '「{topic}」の観点から試作メニューのコンセプトを調整します。',
    '「{topic}」を踏まえた原価率管理の方針を提案します。',
  ],
  finance: [
    '「{topic}」について財務シミュレーションを実施します。数値で裏付けた回答を準備します。',
    '「{topic}」に関するコストと収益性への影響を試算中です。',
    '「{topic}」のリスク・リターンを数値で評価し報告します。',
  ],
  marketing: [
    '「{topic}」はブランディングと集客に直結します。施策案を3パターン提案します。',
    '「{topic}」をターゲット顧客に届けるコミュニケーション戦略を立案中です。',
    '「{topic}」をSNSで効果的に発信するコンテンツ案を作成します。',
  ],
  audit: [
    '【監査】「{topic}」には法的・財務的リスクが潜在しています。専門家への確認を推奨します。',
    '【監査】「{topic}」について他部門計画との整合性を検証しました。懸念事項があります。',
    '【監査】「{topic}」に関するリスクマトリクスを更新しました。対策案を提示します。',
  ],
  _default: [
    '「{topic}」について担当の立場から回答を準備します。',
    '「{topic}」は重要な議題です。詳細を精査してから意見を述べます。',
  ],
}
